/**
 * Copyright (C) 2025 Uppli SAS — Billariz
 *
 * This file is part of Billariz, licensed under the GNU Affero General
 * Public License v3.0 (AGPL-3.0). You may use, modify and distribute
 * this software under the terms of the AGPL-3.0.
 *
 * For commercial use without AGPL obligations, contact:
 * contact@billariz.com | contact@uppli.fr
 * https://billariz.com
 */

import { MultilineCellRenderer } from 'src/components/table/cell/renderer';
import { FILTER_TYPE } from './enums';

import * as Yup from 'yup';

const PARAMETERS_CONFIG = {
  NAME: {
    PERMISSION: 'permissions',
    PERMISSION_ACTION: 'permissionAction',
    PERMISSION_CONDITION: 'permissionCondition',
    PERMISSION_CATEGORY: 'permissionCategory',
    CONTRACT: 'contracts',
    POS: 'pointOfServices',
    CUSTOMERS: 'customers',
    ANALYTIC_CODE: 'analyticCode',
    WEATHERCHANNELCODE: 'weatherChannelCode',
    COUNTRY_CODE: 'countryCode',
    DELIVERY_MODE_CODE: 'deliveryModeCode',
    CUSTOMER_TYPE: 'customerType',
    CUSTOMER_STATUS: 'customerStatus',
    CUSTOMER_CATEGORY: 'customerCategory',
    CONTRACT_STATUS: 'contractStatus',
    CONTRACT_CATEGORY: 'serviceCategory',
    CONTRACT_BILLING_MODE: 'billingMode',
    CONTRACT_BILLING_CYCLE: 'billingCycles',
    CONTRACT_INSTALL_PERIODICITY: 'installPeriodicity',
    BILL_SEGMENT_SCHEMA: 'billSegmentSchema',
    PROFILS: 'profile',
    BILLING_FREQUENCY: 'billingFrequency',
    MARKET: 'market',
    EVENT_ACTION: 'eventAction',
    PERIMETER: 'perimeters',
    PERIMETER_STATUS: 'perimeterStatus',
    PERIMETER_TYPES: 'perimeterTypes',
    POS_DELIVERY_STATE: 'deliveryState',
    POS_DELIVERY_STATUS: 'deliveryStatus',
    POS_CAPACITY_STATUS: 'posCapacityStatus',
    DIRECTION: 'direction',
    DGO: 'dgoCode',
    TGO: 'tgoCode',
    GRID_RATE: 'gridRate',
    POS_TEMPORARY_CONNECTION: 'temporaryConnection',
    POS_TEMPORARY_CONNECTION_TYPE: 'temporaryConnectionType',
    POS_CONFIGURATION_STATUS: 'posConfigurationStatus',
    POS_DATA_STATUS: 'posDataStatus',
    SMART_METER_STATUS: 'smartMeterStatus',
    ACTIVITY_CATEGORY: 'activityCategory',
    ACTIVITY_SUBCATEGORY: 'activitySubCategory',
    ACTIVITY_TYPE: 'activityTypes',
    ACTIVITY_STATUS: 'activityStatus',
    ACTIVITY_ID: 'id',
    ACTIVITY_TEMPLATE_RANK: 'rank',
    ACTIVITY_TEMPLATE_DEFAULT_STATUS: 'defaultStatus',
    EVENT_CATEGORY: 'eventCategory',
    EVENT_SUBCATEGORY: 'eventSubCategory',
    EVENT_TEMPLATE: 'eventTemplates',
    EVENT_EXECUTION_MODE: 'eventExecutionMode',
    EVENT_PERIOD_SYSTEM: 'eventPeriodSystem',
    EVENT_RECURRENT_PERIOD_TYPE: 'eventRecurrencePeriodType',
    EVENT_TRIGGER_DATE_MODE: 'eventTriggerDateMode',
    EVENT_TYPE: 'eventType',
    EVENT_STATUS: 'eventStatus',
    BILL_TYPE: 'billType',
    BILLINGRUN_STATUS: 'billingRunStatus',
    BILL_NATURE: 'billNature',
    BILL_STATUS: 'billStatus',
    SERVICE_STATUS: 'serviceStatus',
    SERVICE_CATEGORY: 'serviceCategory',
    SERVICE_SUBCATEGORY: 'serviceSubCategory',
    TERME_OF_SERVICE_SUBCATEGORY: 'termOfServiceSubCategory',
    TERME_OF_SERVICE_CATEGORY: 'termOfServiceCategory',
    TERME_OF_SERVICE_STATUS: 'termOfServiceStatus',
    RELATION_TYPE: 'relationType',
    BILL_SEGMENT_STATUS: 'billSegmentStatus',
    ACTOR_ROLE: 'actorRole',
    THIRD_TYPE: 'thirdType',
    SERVICE_TYPE_SUBCATEGORY: 'serviceSubCategory',
    SERVICE_TYPE_CATEGORY: 'serviceCategory',
    SERVICE_ELEMENT_TYPE_CATEGORY: 'serviceElementTypeCategory',
    SELLER: 'seller',
    CHANNEL: 'channel',
    PAYMENT_MODE: 'paymentMode',
    POS_CATEGORY: 'posCategory',
    TOU_GROUP: 'touGroup',
    BILLING_MODE: 'billingMode',
    TOS_TYPE_SUBCATEGORY: 'tosSubCategory',
    PRICE_MODE: 'priceMode',
    PRICE_UNIT: 'priceUnit',
    PRICE_TYPE: 'priceType',
    UNIT_OF_UNIT_PRICE: 'unitOfUnitPrice',
    REF_DATE_FIXED_PRICE: 'refDateForFixedPrice',
    SERVICE_ELEMENT_CATEGORY: 'serviceElementCategory',
    SERVICE_ELEMENT_SUB_CATEGORY: 'serviceElementSubCategory',
    SERVICE_ELEMENT_TYPES: 'serviceElementTypes',
    SERVICE_TYPES: 'serviceTypes',
    TOS_TYPES: 'termOfServiceTypes',
    VAT_RATE: 'vatRate',
    SQ_TYPE: 'sqType',
    ACCOUNTING_SHEME: 'accountingScheme',
    BILLING_SHEME: 'billingScheme',
    SERVICE_ELEMENT_STATUS: 'serviceElementStatus',
    FACTOR_TYPE: 'factorType',
    OPERAND_TYPE: 'operandType',
    THRESHOLD_TYPE: 'thresholdType',
    THRESHOLD_BASE: 'thresholdBase',
    RATE_CATEGORY: 'rateCategory',
    RATE_SUB_CATEGORY: 'rateSubCategory',
    RATE_TYPES: 'rateTypes',
    INSTALLMENT_FREQUENCY: 'installmentFrequency',
    UNIT_PRICE: 'priceUnit',
    SOURCE: 'source',
    POS_DATA_SOURCE: 'posDataSource',
    METER_READ_SOURCE: 'meterReadSource',
    TOU: 'tou',
    MEASURE_TYPE: 'measureType',
    LEGAL_FORM: 'legalForm',
    NACE_CODE: 'naceCode',
    ENTITY_CATEGORY: 'entityCategory',
    ENTITY_SUB_CATEGORY: 'entitySubCategory',
    GROUP_CATEGORY: 'groupCategory',
    GROUP_SUB_CATEGORY: 'groupSubCategory',
    LANGUAGE: 'language',
    USER_ROLE: 'userRole',
    USERS: 'users',
    TITLE_CODE: 'titleCode',
    USER_STATUS: 'userStatus',
    ORGANISMS: 'organisms',
    GROUPS: 'groups',
    OBJECT_TYPE: 'objectType',
    METER_READ_QUALITY: 'meterReadQuality',
    LAUNCHER_TAG_TYPE: 'launcherTagTypes',
    METER_TYPE: 'meterType',
    CAPACITY_TYPE: 'capacityType',
    ESTMATION_TYPE: 'estimateType',
    READING_CYCLE: 'readingCycles',
    METER_READ_TYPE: 'meterReadType',
    METER_READ_STATUS: 'meterReadStatus',
    METER_READ_CONTEXT: 'meterReadContext',
    DOMICILIATION_STATUS: 'domicilationStatus',
    BILLABLE_CHARGE_STATUS: 'billableChargeStatus',
    BILLABLE_CHARGE_SOURCE: 'billableChargeSource',
    BILLABLE_CHARGE_CONTEXT: 'billableChargeContext',
    BILLABLE_CHARGE_TYPE: 'billableChargeTypes',
    ARTICLE_TYPE: 'articleTypes',
    ARTICLE_STATUS: 'articleStatus',
  },
  COLUMNS: [
    {
      id: 'id',
      label: 'Parameter.TableHeader.id',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'id', type: 'text' }],
      },
    },
    {
      id: 'parameterType',
      label: 'Parameter.TableHeader.parameterType',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'type', type: 'text' }],
      },
    },
    {
      id: 'category',
      label: 'Parameter.TableHeader.category',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [
          { value: 'category', type: 'text' },
          { value: 'subCategory', type: 'text' },
        ],
      },
    },
    {
      id: 'parameter',
      label: 'Parameter.TableHeader.parameter',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'name', type: 'text' }],
      },
    },
    {
      id: 'value',
      label: 'Parameter.TableHeader.value',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'value', type: 'text' }],
      },
    },
    {
      id: 'label',
      label: 'Parameter.TableHeader.label',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'defaultLabel', type: 'text' }],
      },
    },
    {
      id: 'period',
      label: 'Parameter.TableHeader.period',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'startDate', type: 'date' }],
      },
    },
  ],
  FILTERS: {
    CATEGORY: {
      index: 0,
      id: 'type',
      label: 'Parameter.FilterLabels.type',
      type: FILTER_TYPE.TAB,
      size: {
        xs: 12,
        sm: 6,
        md: 2,
        lg: 2,
      },
      row: 1,
      defaultValue: '*',
      parameterName: 'parameterType',
    },
    TYPE: {
      index: 1,
      id: 'category',
      label: 'Parameter.FilterLabels.category',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      row: 1,
      parameterName: 'parameterCategory',
    },
    SUB_CATEGORY: {
      index: 2,
      id: 'subCategory',
      label: 'Parameter.FilterLabels.subCategory',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      row: 1,
      parameterName: 'parameterSubCategory',
    },
    PARAMETER: {
      index: 3,
      id: 'name',
      label: 'Parameter.FilterLabels.name',
      type: 'TextField',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '',
    },
    ID: {
      index: 4,
      id: 'id',
      label: 'Parameter.FilterLabels.id',
      type: 'TextField',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '',
    },
  },
  FORMS: {
    PARAMETER: {
      FIELDS: [
        {
          name: 'type',
          label: 'Parameter.FilterLabels.type',
          parameterName: 'parameterType',
          type: 'RHFSelect',
          validation: Yup.string().required('Error.isRequired'),
          getCurrentValue: (parameter) => parameter.type,
          size: {
            xs: 3,
            sm: 3,
            md: 3,
            lg: 3,
          },
        },
        {
          name: 'category',
          label: 'Parameter.FilterLabels.category',
          parameterName: 'parameterCategory',
          type: 'RHFSelect',
          validation: Yup.string().required('Error.isRequired'),
          getCurrentValue: (parameter) => parameter.category,
          size: {
            xs: 3,
            sm: 3,
            md: 3,
            lg: 3,
          },
        },
        {
          name: 'subCategory',
          label: 'Parameter.FilterLabels.subCategory',
          parameterName: 'parameterSubCategory',
          type: 'RHFSelect',
          // validation: Yup.string().required('subCategory is required'),
          getCurrentValue: (parameter) => parameter.subCategory,
          getDefaultValue: () => '*',
          size: {
            xs: 3,
            sm: 3,
            md: 3,
            lg: 3,
          },
        },
        {
          name: 'name',
          label: 'Parameter.FilterLabels.name',
          type: 'RHFTextField',
          validation: Yup.string().required('Error.isRequired'),
          getCurrentValue: (parameter) => parameter.name,
          size: {
            xs: 3,
            sm: 3,
            md: 3,
            lg: 3,
          },
        },
        {
          name: 'value',
          label: 'Parameter.FilterLabels.value',
          type: 'RHFTextField',
          validation: Yup.string().required('Error.isRequired'),
          getCurrentValue: (parameter) => parameter.value,
          size: {
            xs: 3,
            sm: 3,
            md: 3,
            lg: 3,
          },
        },
        {
          name: 'startDate',
          label: 'Parameter.FilterLabels.startDate',
          type: 'RHFDatePicker',
          validation: Yup.string().required('Error.isRequired'),
          getCurrentValue: (parameter) => parameter.startDate,
          size: {
            xs: 3,
            sm: 3,
            md: 3,
            lg: 3,
          },
        },
        {
          name: 'defaultLabel',
          label: 'Parameter.FilterLabels.defaultLabel',
          type: 'RHFTextField',
          validation: Yup.string().required('Error.isRequired'),
          getCurrentValue: (parameter) => parameter.defaultLabel,
          size: {
            xs: 3,
            sm: 3,
            md: 3,
            lg: 3,
          },
        },
        {
          name: 'standardLabel',
          label: 'Parameter.FilterLabels.standardLabel',
          type: 'RHFTextField',
          validation: Yup.string().required('Error.isRequired'),
          getCurrentValue: (parameter) => parameter.standardLabel,
          size: {
            xs: 3,
            sm: 3,
            md: 3,
            lg: 3,
          },
        },
      ],
    },
  },
};

export default PARAMETERS_CONFIG;
