/**
 * Copyright (C) 2025 Uppli SAS — Billariz
 *
 * This file is part of Billariz, licensed under the GNU Affero General
 * Public License v3.0 (AGPL-3.0). You may use, modify and distribute
 * this software under the terms of the AGPL-3.0.
 *
 * For commercial use without AGPL obligations, contact:
 * contact@billariz.com | contact@uppli.fr
 * https://billariz.com
 */

import * as Yup from 'yup';
import PARAMETERS_CONFIG from './parameters';
import { MultilineCellRenderer } from 'src/components/table/cell/renderer';
import { FILTER_TYPE } from './enums';

const SERVICE_START_OPTION_CONFIG = {
  COLUMNS: [
    {
      id: 'service',
      label: 'Service.TableHeader.id',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [
          { value: 'service', type: 'text' },
          { value: 'id', type: 'text' },
        ],
      },
    },
    {
      id: 'seller',
      label: 'Service.TableHeader.seller',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [
          { value: 'seller', type: 'text' },
          { value: 'channel', type: 'text' },
        ],
      },
    },
    {
      id: 'category',
      label: 'Service.TableHeader.category',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [
          { value: 'serviceCategory', type: 'text' },
          { value: 'serviceSubCategory', type: 'text' },
        ],
      },
    },
    {
      id: 'period',
      label: 'Service.TableHeader.period',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [
          { value: 'startDate', type: 'date' },
          { value: 'endDate', type: 'date' },
        ],
      },
    },
    {
      id: 'market',
      label: 'Service.TableHeader.market',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'market', type: 'text' }],
      },
    },
    {
      id: 'customer',
      label: 'Service.TableHeader.customer',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [
          { value: 'customerType', type: 'text' },
          { value: 'customerCategory ', type: 'text' },
        ],
      },
    },
    {
      id: 'billingMode',
      label: 'Service.TableHeader.billingMode',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'billingMode', type: 'text' }],
      },
    },
    {
      id: 'paymentMode',
      label: 'Service.TableHeader.paymentMode',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'paymentMode', type: 'text' }],
      },
    },
    {
      id: 'posCategory',
      label: 'Service.TableHeader.posCategory',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'posCategory', type: 'text' }],
      },
    },
    {
      id: 'direction',
      label: 'Service.TableHeader.direction',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'serviceDirection', type: 'text' }],
      },
    },
    {
      id: 'dso',
      label: 'Service.TableHeader.dso',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [
          { value: 'tso', type: 'text' },
          { value: 'dso', type: 'text' },
        ],
      },
    },
    {
      id: 'consumptionThreshold',
      label: 'Service.TableHeader.consumptionThreshold',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'consumptionThreshold', type: 'text' }],
      },
    },
    {
      id: 'touGroup',
      label: 'Service.TableHeader.touGroup',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'touGroup', type: 'text' }],
      },
    },
    {
      id: 'tosType',
      label: 'Service.TableHeader.tosType',
      align: 'left',
      cell: {
        renderer: MultilineCellRenderer,
        value: [{ value: 'tosType', type: 'text' }],
      },
    },
  ],
  FILTERS: {
    CATEGORY: {
      index: 0,
      id: 'category',
      label: 'Service.FilterLabels.category',
      type: FILTER_TYPE.TAB,
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.SERVICE_TYPE_CATEGORY,
    },
    SUBCATEGORY: {
      index: 1,
      id: 'subCategory',
      label: 'Service.FilterLabels.subCategory',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.SERVICE_TYPE_SUBCATEGORY,
    },
    SELLER: {
      index: 2,
      id: 'seller',
      label: 'Service.seller',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.SELLER,
    },
    CHANNEL: {
      index: 3,
      id: 'channel',
      label: 'Service.channel',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.CHANNEL,
    },
    MARKET: {
      index: 4,
      id: 'market',
      label: 'Service.TableHeader.market',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.MARKET,
    },
    CUSTOMER_TYPE: {
      index: 5,
      id: 'customerType',
      label: 'Service.customerType',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.CUSTOMER_TYPE,
    },
    CUSTOMER_CATEGORY: {
      index: 6,
      id: 'customerCategory',
      label: 'Service.customerCategory',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.CUSTOMER_CATEGORY,
    },
    BILLING_MODE: {
      index: 7,
      id: 'billingMode',
      label: 'Service.TableHeader.billingMode',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.BILLING_MODE,
    },
    PEYMENT_MODE: {
      index: 8,
      id: 'paymentMode',
      label: 'Service.TableHeader.paymentMode',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.PAYMENT_MODE,
    },
    POS_CATEGORY: {
      index: 9,
      id: 'posCategory',
      label: 'Service.TableHeader.posCategory',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.POS_CATEGORY,
    },
    DIRECTION: {
      index: 10,
      id: 'direction',
      label: 'Service.TableHeader.direction',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.DIRECTION,
    },
    DSO: {
      index: 11,
      id: 'dso',
      label: 'Service.dso',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.DGO,
    },
    TSO: {
      index: 12,
      id: 'tso',
      label: 'Service.tso',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.TGO,
    },
    TOU_GROUP: {
      index: 13,
      id: 'touGroup',
      label: 'Service.TableHeader.touGroup',
      type: 'selectBox',
      size: {
        xs: 12,
        sm: 6,
        md: 3,
        lg: 3,
      },
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.TOU_GROUP,
    },
    SERVICE_TYPE: {
      index: 14,
      id: 'serviceType',
      label: 'Service.FilterLabels.type',
      type: 'autocomplete',
      category: 'service',
      enumId: 'serviceType',
      size: {
        xs: 12,
        sm: 6,
        md: 4,
        lg: 4,
      },
      addAllValue: true,
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.SERVICE_TYPES,
    },
    TOS_TYPE: {
      index: 15,
      id: 'tosType',
      label: 'Service.TableHeader.tosType',
      type: 'autocomplete',
      category: 'termOfService',
      enumId: 'id',
      size: {
        xs: 12,
        sm: 6,
        md: 5,
        lg: 5,
      },
      addAllValue: true,
      defaultValue: '*',
      parameterName: PARAMETERS_CONFIG.NAME.TOS_TYPES,
    },
  },
  FORMS: {
    FIELDS: [
      {
        name: 'service',
        label: 'Service.service',
        type: 'RHFTextField',
        size: {
          xs: 12,
          sm: 6,
          md: 6,
          lg: 6,
        },
        getCurrentValue: (parameter) => parameter.service,
      },
      {
        name: 'serviceCategory',
        label: 'Parameter.FilterLabels.category',
        parameterName: PARAMETERS_CONFIG.NAME.SERVICE_TYPE_CATEGORY,
        type: 'RHFSelect',
        addAllValue: true,
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.serviceCategory,
        size: {
          xs: 3,
          sm: 3,
          md: 3,
          lg: 3,
        },
      },
      {
        name: 'serviceSubCategory',
        label: 'Parameter.FilterLabels.subCategory',
        parameterName: PARAMETERS_CONFIG.NAME.SERVICE_TYPE_SUBCATEGORY,
        type: 'RHFSelect',
        addAllValue: true,
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.serviceSubCategory,
        size: {
          xs: 3,
          sm: 3,
          md: 3,
          lg: 3,
        },
      },
      {
        name: 'seller',
        label: 'Service.seller',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        addAllValue: true,
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.seller,
        parameterName: PARAMETERS_CONFIG.NAME.SELLER,
      },
      {
        name: 'channel',
        label: 'Service.channel',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        addAllValue: true,
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.channel,
        parameterName: PARAMETERS_CONFIG.NAME.CHANNEL,
      },
      {
        name: 'market',
        label: 'Service.TableHeader.market',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        addAllValue: true,
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.market,
        parameterName: PARAMETERS_CONFIG.NAME.MARKET,
      },
      {
        name: 'customerType',
        label: 'Service.customerType',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.customerType,
        parameterName: PARAMETERS_CONFIG.NAME.CUSTOMER_TYPE,
      },
      {
        name: 'customerCategory',
        label: 'Service.customerCategory',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.customerCategory,
        parameterName: PARAMETERS_CONFIG.NAME.CUSTOMER_CATEGORY,
      },
      {
        name: 'billingMode',
        label: 'Service.TableHeader.billingMode',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.billingMode,
        parameterName: PARAMETERS_CONFIG.NAME.BILLING_MODE,
      },
      {
        name: 'paymentMode',
        label: 'Service.TableHeader.paymentMode',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.paymentMode,
        parameterName: PARAMETERS_CONFIG.NAME.PAYMENT_MODE,
      },
      {
        name: 'posCategory',
        label: 'Service.TableHeader.posCategory',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.posCategory,
        parameterName: PARAMETERS_CONFIG.NAME.POS_CATEGORY,
      },
      {
        name: 'serviceDirection',
        label: 'Service.TableHeader.direction',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.serviceDirection,
        parameterName: PARAMETERS_CONFIG.NAME.DIRECTION,
      },
      {
        name: 'dgoCode',
        label: 'Service.dso',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.dgoCode,
        parameterName: PARAMETERS_CONFIG.NAME.DGO,
      },
      {
        name: 'tgoCode',
        label: 'Service.tso',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.tgoCode,
        parameterName: PARAMETERS_CONFIG.NAME.TGO,
      },
      {
        name: 'touGroup',
        label: 'Service.TableHeader.touGroup',
        type: 'RHFSelect',
        size: {
          xs: 12,
          sm: 6,
          md: 3,
          lg: 3,
        },
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.touGroup,
        parameterName: PARAMETERS_CONFIG.NAME.TOU_GROUP,
      },
      {
        name: 'consumptionThreshold',
        label: 'Service.TableHeader.consumptionThreshold',
        type: 'RHFTextField',
        size: {
          xs: 12,
          sm: 6,
          md: 6,
          lg: 6,
        },
        getCurrentValue: (parameter) => parameter.consumptionThreshold,
      },
      {
        name: 'startDate',
        label: 'Parameter.FilterLabels.startDate',
        type: 'RHFDatePicker',
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.startDate,
        size: {
          xs: 3,
          sm: 3,
          md: 3,
          lg: 3,
        },
      },
      {
        name: 'endDate',
        label: 'Parameter.FilterLabels.endDate',
        type: 'RHFDatePicker',
        getCurrentValue: (parameter) => parameter.endDate,
        size: {
          xs: 3,
          sm: 3,
          md: 3,
          lg: 3,
        },
      },
      {
        name: 'tosType',
        label: 'Service.TableHeader.tosType',
        type: 'RHFAutocomplete',
        category: 'termOfService',
        size: {
          xs: 12,
          sm: 6,
          md: 6,
          lg: 6,
        },
        addAllValue: true,
        validation: Yup.string().required('Error.isRequired'),
        getCurrentValue: (parameter) => parameter.tosType,
        parameterName: PARAMETERS_CONFIG.NAME.TOS_TYPES,
      },
    ],
  },
};

export default SERVICE_START_OPTION_CONFIG;
