/**
 * Copyright (C) 2025 Uppli SAS — Billariz
 *
 * This file is part of Billariz, licensed under the GNU Affero General
 * Public License v3.0 (AGPL-3.0). You may use, modify and distribute
 * this software under the terms of the AGPL-3.0.
 *
 * For commercial use without AGPL obligations, contact:
 * contact@billariz.com | contact@uppli.fr
 * https://billariz.com
 */

const ENDPOINTS = {
  CUSTOMERS: '/customers',
  CUSTOMER: '/customers/{{customerId}}',
  EVENT: '/events/{{eventId}}',
  EVENT_TEMPLATE_FIND: '/eventTemplates/search/findEventTemplate',
  CUSTOMER_INDIVIDUAL: '/customers/{{customerId}}/individual',
  CUSTOMER_CONTACT: '/customers/{{customerId}}/contact',
  CUSTOMER_COMPANY: '/customers/{{customerId}}/company',
  CUSTOMER_ADDRESS: '/customers/{{customerId}}/address',
  PARAMETERS_BY_NAME: '/parameters/search/findEnumParameters?name={{name}}',
  PARAMETERS_ALL: 'parameters/search/findAll',
  PARAMETERS_FIND: '/parameters/search/findParameter',
  PARAMETERS_BY_NAME_AND_CATEGORY:
    '/parameters/search/findEnumParameters?name={{name}}&category={{category}}',
  PARAMETER: '/parameters/{{parameterId}}',
  PARAMETER_AUTOCOMPLETE: '/{{name}}/search/',
  ACTIVITY_TYPE_FIND: '/activityTypes/search/findActivityType',
  ACTIVITY_TEMPLATE_FIND: '/activityTemplates/search/findActivityTemplate',
  ACTIVITY_BY_TYPE:
    '/activityTypes/search/findActivityType?category={{category}}&subCategory={{subCategory}}',
  CUSTOMER_FIND_RESIDENTIAL: '/customers/search/findResidential',
  CUSTOMER_FIND_PROFESSIONNAL: '/customers/search/findProfessionnal',
  CUSTOMER_APPLICATION_CHART: 'customers/search/customersApplicationChart',
  CUSTOMER_CONVERTED_CHART: 'customers/search/customersConvertedChart',
  CUSTOMER_LED_CHART: 'customers/search/customersLeadChart',
  CUSTOMER_FIND_BY_ID: '/customers/search/findCustomer',
  CONTRACTS_FIND: '/contracts/search/findContract',
  CONTRACT_FIND_BY_ID: '/contracts/search/findContractById',
  PERIMETERS_FIND: '/perimeters/search/findPerimeter',
  POS_FIND: '/pointOfServices/search/findPointOfService',
  POS: '/pointOfServices/{{posId}}',
  ACTIVITIES_FIND: '/activities/search/findActivity',
  ACTIVITIES: '/activities/{{activityId}}',
  EVENTS_FIND: '/events/search/findEvent',
  CHARTS_FIND: '/charts/dashboard',
  CHARTS_BY_NAME: '/charts/{{chartName}}',
  BILLS_FIND: '/bills/search/findBill',
  BILLINGRUNS_FIND: '/billingRuns/search/findBillingRun',
  ADDRESSES: '/addresses',
  ADDRESS: '/addresses/{{addressId}}',
  INDIVIDUAL: '/individuals/{{individualId}}',
  CONTACT: '/contacts/{{contactId}}',
  COMPANY: '/companies/{{companyId}}',
  CONTRACTS: '/contracts/{{contractId}}',
  CONTRACT_POS: '/contractPointOfServices/{{contractId}}',
  PERIMETERS: '/perimeters/{{perimeterId}}',
  POS_CONFIGURATION: '/pointOfServiceConfigurations/{{posConfigurationId}}',
  POS_CONFIGURATION_FIND:
    '/pointOfServiceConfigurations/search/findPosConfiguration',
  POS_CAPACITY: '/pointOfServiceCapacities/{{capacityId}}',
  POS_CAPACITY_FIND: '/pointOfServiceCapacities/search/findPosCapacity',
  POS_ESTIMATE_FIND: '/pointOfServiceEstimates/search/findPosEstimate',
  POS_ESTIMATE: '/pointOfServiceEstimates/{{estimateId}}',
  SERVICE_ELEMENT: '/serviceElements/{{serviceElementId}}',
  CONSUMPTION_FIND: '/meterReads/search/findMeterRead',
  CONSUMPTION: '/meterReads/{{consumptionId}}',
  BILLABLE_CHARGE: '/billableCharges/{{billableChargeId}}',
  BILLABLE_CHARGE_FIND: '/billableCharges/search/findBillableCharge',
  CONSUMPTION_FIND_BY_ID: '/meterReads/{{meterReadId}}',
  CONSUMPTION_FIND_RELATION: '/meterReads/{{meterReadId}}/relations',
  BILLABLE_CHARGE_FIND_RELATION:
    '/billableCharges/{{billableChargeId}}/relations',
  METER_UPDATE: '/meters/{{meterId}}',
  METER_FIND: '/meters/search/findMeter',
  ARTICLE_FIND: '/articles/search/findArticle',
  ARTICLE: '/articles/{{articleId}}',
  METER_READS_DETAILS_FIND: '/meterReadDetails/search/findMeterReadDetail',
  METER_READS_DETAILS: '/meterReadDetails/{{meterReadDetailId}}',
  SERVICES_FIND: '/services/search/findService',
  TERM_OF_SERVICES_FIND: '/termOfServices/search/findTermOfService',
  RELATIONS_FIND: '/relations/search/findRelation',
  JOURNAL_FIND: '/journals/search/findJournal',
  JOURNAL: '/journals/{{journalId}}',
  SERVICE_ELEMENTS_FIND: '/serviceElements/search/findServiceElement',
  BILL_SEGMENTS_FIND: '/billSegments/search/findBillSegment',
  BILL_SEGMENT: '/billSegments/{{billSegmentId}}',
  BILL_BY_ID_FIND: '/bills/search/findBillById',
  BILLINGRUN_BY_ID_FIND: '/billingRuns/search/findBillingRunById',
  ACTORS_FIND: '/actors/search/findActor',
  ACTOR: '/actors/{{actorId}}',
  CUSTOMERS_FIND: '/customers/search/findCustomer',
  SERVICE_TYPES_FIND: '/serviceTypes/search/findServiceType',
  SERVICE_TYPE: '/serviceTypes/{{serviceTypeId}}',
  SERVICE_START_OPTIONS_FIND:
    '/serviceStartOptions/search/findServiceStartOption',
  SERVICE_START_OPTION: '/serviceStartOptions/{{serviceStartOptionId}}',
  TOS_TYPE: '/termOfServiceTypes/{{tosTypeId}}',
  TOS_TYPES_FIND: '/termOfServiceTypes/search/findTermOfServiceType',
  TOS_START_OPTIONS_FIND:
    '/termOfServiceStartOptions/search/findTermOfServiceStartOption',
  TOS_START_OPTION: '/termOfServiceStartOptions/{{tosStartOptionId}}',
  SERVICE_ELEMENT_TYPES_FIND:
    '/serviceElementTypes/search/findServiceElementType',
  SERVICE_ELEMENT_TYPE: '/serviceElementTypes/{{serviceElementTypeId}}',
  SE_START_OPTIONS_FIND:
    '/serviceElementStartOptions/search/findServiceElementStartOption',
  SERVICE_ELEMENT_START_OPTION:
    '/serviceElementStartOptions/{{seStartOptionId}}',
  RATE_TYPES_FIND: '/rateTypes/search/findRateType',
  RATE_TYPE: '/rateTypes/{{rateType}}',
  SERVICE: '/services/{{serviceId}}',
  TOS: '/termOfServices/{{tosId}}',
  ACTIVITY_TEMPLATE: '/activityTemplates/{{activityTemplateId}}',
  ACTIVITY_TYPE: '/activityTypes/{{activityTypeId}}',
  EVENT_TEMPLATE: '/eventTemplates/{{eventTemplateId}}',
  RATE: '/rates/{{rateId}}',
  RATE_FIND: '/rates/search/findRate',
  BILL: '/bills/{{billId}}',
  BILLINGRUN: '/billingRuns/{{billingRunId}}',
  ENTITY_FIND: '/organisms/search/findOrganism',
  ENTITY: '/organisms/{{entityId}}',
  GROUP_FIND: '/groups/search/findGroup',
  GROUP: '/groups/{{groupId}}',
  USER_FIND: '/users/search/findUser',
  THIRD: '/thirds/{{thirdId}}',
  THIRD_FIND: '/thirds/search/findThird',
  USER: '/users/{{userId}}',
  OBJECT_PROCESS_RULES_FIND: '/objectProcessRules/search/findObjectProcessRule',
  OBJECT_PROCESS_RULES: '/objectProcessRules/{{objectProcessRuleId}}',
  POSTAL_CODE_FIND: '/postalCodes/search/findPostalCode',
  USER_PERMISSIONS_FIND: '/userPermissions/search/findUserPermission',
  USER_PERMISSIONS: '/userPermissions/{{userPermissionId}}',
  USER_ROLES_FIND: '/userRoles/search/findUserRole',
  USER_ROLE: '/userRoles/{{userRoleId}}',
  PERMISSIONS_FIND: '/permissions/search/findPermission',
  PERMISSION: '/permissions/{{permissionId}}',
  ROLE: '/roles/{{roleId}}',
  ROLES_FIND: '/roles/search/findRole',
  ROLE_PERMISSION_FIND: '/rolePermissions/search/findRolePermission',
  ROLE_PERMISSION: '/rolePermissions/{{rolePermissionId}}',
  POSTAL_CODE: '/postalCodes/{{postalCodeId}}',
  GEO_REF_FIND: '/marketGeoRefs/search/findMarketGeoRef',
  GEO_REF: '/marketGeoRefs/{{geoRefId}}',
  CLIMATIC_REF_FIND: '/climaticRefs/search/findClimaticRef',
  CLIMATIC_REF: '/climaticRefs/{{climaticRefId}}',
  LANGUAGE_MAPPING_FIND: 'languageMappings',
  DOWNLOAD_BILL: '/download/bill/{{billId}}',
  FIND_PERMISSIONS: 'permissions/search/findPermissionsByUserNameAndEntity',
};

export default ENDPOINTS;
